name: CI - inf83 API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Vérifier que le workflow fonctionne
        run: echo "Le workflow CI fonctionne correctement"